export type AsrLanguage = string;

export const ASR_LANGUAGES: { id: string; label: string }[] = [
  { id: "auto", label: "自動偵測" },
  { id: "zh", label: "繁體中文" },
  { id: "yue", label: "粵語" },
  { id: "en", label: "英語" },
  { id: "ja", label: "日語" },
  { id: "ko", label: "韓語" },
  { id: "es", label: "西班牙語" },
  { id: "fr", label: "法語" },
  { id: "de", label: "德語" },
  { id: "pt", label: "葡萄牙語" },
  { id: "it", label: "義大利語" },
  { id: "ru", label: "俄語" },
  { id: "vi", label: "越南語" },
  { id: "th", label: "泰語" },
  { id: "id", label: "印尼語" },
  { id: "ms", label: "馬來語" },
  { id: "hi", label: "印地語" },
  { id: "ar", label: "阿拉伯語" },
  { id: "tr", label: "土耳其語" },
  { id: "pl", label: "波蘭語" },
  { id: "nl", label: "荷蘭語" },
  { id: "sv", label: "瑞典語" },
  { id: "uk", label: "烏克蘭語" },
  { id: "cs", label: "捷克語" },
  { id: "ro", label: "羅馬尼亞語" },
  { id: "hu", label: "匈牙利語" },
  { id: "el", label: "希臘語" },
  { id: "he", label: "希伯來語" },
  { id: "fa", label: "波斯語" },
  { id: "ur", label: "烏爾都語" },
  { id: "bn", label: "孟加拉語" },
  { id: "ta", label: "泰米爾語" },
  { id: "te", label: "泰盧固語" },
  { id: "mr", label: "馬拉地語" },
  { id: "gu", label: "古吉拉特語" },
  { id: "kn", label: "卡納達語" },
  { id: "ml", label: "馬拉雅拉姆語" },
  { id: "pa", label: "旁遮普語" },
  { id: "ne", label: "尼泊爾語" },
  { id: "si", label: "僧伽羅語" },
  { id: "my", label: "緬甸語" },
  { id: "km", label: "高棉語" },
  { id: "lo", label: "寮語" },
  { id: "tl", label: "菲律賓語" },
  { id: "jw", label: "爪哇語" },
  { id: "su", label: "巽他語" },
  { id: "ca", label: "加泰隆尼亞語" },
  { id: "gl", label: "加利西亞語" },
  { id: "eu", label: "巴斯克語" },
  { id: "cy", label: "威爾斯語" },
  { id: "ga", label: "愛爾蘭語" },
  { id: "is", label: "冰島語" },
  { id: "da", label: "丹麥語" },
  { id: "no", label: "挪威語" },
  { id: "fi", label: "芬蘭語" },
  { id: "et", label: "愛沙尼亞語" },
  { id: "lv", label: "拉脫維亞語" },
  { id: "lt", label: "立陶宛語" },
  { id: "sk", label: "斯洛伐克語" },
  { id: "sl", label: "斯洛維尼亞語" },
  { id: "hr", label: "克羅埃西亞語" },
  { id: "sr", label: "塞爾維亞語" },
  { id: "bs", label: "波士尼亞語" },
  { id: "mk", label: "馬其頓語" },
  { id: "bg", label: "保加利亞語" },
  { id: "sq", label: "阿爾巴尼亞語" },
  { id: "af", label: "南非荷蘭語" },
  { id: "sw", label: "斯瓦希里語" },
  { id: "am", label: "阿姆哈拉語" },
  { id: "ha", label: "豪薩語" },
  { id: "yo", label: "約魯巴語" },
  { id: "so", label: "索馬利亞語" },
  { id: "mg", label: "馬達加斯加語" },
  { id: "mi", label: "毛利語" },
  { id: "haw", label: "夏威夷語" },
  { id: "hy", label: "亞美尼亞語" },
  { id: "ka", label: "喬治亞語" },
  { id: "az", label: "亞塞拜然語" },
  { id: "kk", label: "哈薩克語" },
  { id: "uz", label: "烏茲別克語" },
  { id: "mn", label: "蒙古語" },
  { id: "bo", label: "藏語" },
  { id: "ug", label: "維吾爾語" },
  { id: "ps", label: "普什圖語" },
  { id: "sd", label: "信德語" },
  { id: "sa", label: "梵語" },
  { id: "la", label: "拉丁語" },
  { id: "mt", label: "馬爾他語" },
  { id: "br", label: "布列塔尼語" },
  { id: "oc", label: "奧克語" },
  { id: "tt", label: "韃靼語" },
  { id: "ba", label: "巴什基爾語" },
  { id: "be", label: "白俄羅斯語" },
  { id: "fo", label: "法羅語" },
  { id: "ht", label: "海地克里奧爾語" },
  { id: "lb", label: "盧森堡語" },
  { id: "ln", label: "林格拉語" },
  { id: "nn", label: "新挪威語" },
  { id: "sn", label: "修納語" },
  { id: "tk", label: "土庫曼語" },
  { id: "yi", label: "意第緒語" },
  { id: "as", label: "阿薩姆語" },
];

export function whisperLanguage(code: string) {
  if (!code || code === "auto") return "";
  if (code === "zh-TW" || code === "zh-CN") return "zh";
  return code;
}

export function isChineseLang(code: string) {
  return code === "auto" || code === "zh" || code === "yue" || code.startsWith("zh");
}

export function languageLabel(code: string) {
  return ASR_LANGUAGES.find((item) => item.id === code)?.label ?? code;
}

export const TRANSLATE_TARGETS: { id: string; label: string }[] = [
  { id: "en", label: "英語" },
  { id: "zh-TW", label: "台灣繁體中文" },
  { id: "ja", label: "日語" },
  { id: "ko", label: "韓語" },
  { id: "es", label: "西班牙語" },
  { id: "fr", label: "法語" },
  { id: "de", label: "德語" },
  { id: "vi", label: "越南語" },
  { id: "th", label: "泰語" },
  { id: "id", label: "印尼語" },
];
